// ============================================
// VidyaFrame — Seed Data (from Maths_topics.md)
// ============================================

import { Asset, Category, ClassInfo, Testimonial, FAQItem, StatsItem, NavItem } from './types';

// ─── CATEGORIES ───────────────────────────────────────────────
export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Chart',
    slug: 'charts',
    description: 'Beautiful educational charts for classroom walls and learning activities',
    icon: '📊',
    count: 35,
    gradient: 'from-teal-500 to-cyan-500',
  },
  {
    id: 'cat-2',
    name: 'Worksheet',
    slug: 'worksheets',
    description: 'Printable practice worksheets for homework and classroom exercises',
    icon: '📝',
    count: 18,
    gradient: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'cat-3',
    name: 'Certificate',
    slug: 'certificates',
    description: 'Award certificates to motivate and recognize student achievement',
    icon: '🏆',
    count: 4,
    gradient: 'from-amber-500 to-orange-500',
  },
  {
    id: 'cat-4',
    name: 'Poster',
    slug: 'posters',
    description: 'Eye-catching posters for classroom decoration and learning displays',
    icon: '🖼️',
    count: 1,
    gradient: 'from-purple-500 to-pink-500',
  },
];

// ─── CLASS LEVELS ─────────────────────────────────────────────
export const classLevels: ClassInfo[] = [
  { level: 'Nursery', label: 'Nursery', slug: 'nursery', gradient: 'from-pink-400 to-rose-500', icon: '🧒', count: 10 },
  { level: 'LKG', label: 'LKG', slug: 'lkg', gradient: 'from-orange-400 to-amber-500', icon: '👶', count: 12 },
  { level: 'UKG', label: 'UKG', slug: 'ukg', gradient: 'from-yellow-400 to-lime-500', icon: '🎒', count: 14 },
  { level: '1', label: 'Class 1', slug: 'class-1', gradient: 'from-emerald-400 to-teal-500', icon: '📗', count: 13 },
  { level: '2', label: 'Class 2', slug: 'class-2', gradient: 'from-cyan-400 to-blue-500', icon: '📘', count: 1 },
  { level: '3', label: 'Class 3', slug: 'class-3', gradient: 'from-blue-400 to-indigo-500', icon: '📙', count: 0 },
  { level: '4', label: 'Class 4', slug: 'class-4', gradient: 'from-violet-400 to-purple-500', icon: '📕', count: 0 },
  { level: '5', label: 'Class 5', slug: 'class-5', gradient: 'from-fuchsia-400 to-pink-500', icon: '📓', count: 0 },
];

// ─── NAVIGATION ───────────────────────────────────────────────
export const navItems: NavItem[] = [
  { label: 'Charts', href: '/charts' },
  { label: 'Worksheets', href: '/worksheets' },
  { label: 'Certificates', href: '/certificates' },
  { label: 'Posters', href: '/posters' },
];

// ─── STATS ────────────────────────────────────────────────────
export const stats: StatsItem[] = [
  { label: 'Educational Charts', value: '1,000', suffix: '+', icon: '/hero/charts.webp' },
  { label: 'Practice Worksheets', value: '700', suffix: '+', icon: '/hero/worksheet.webp' },
  { label: 'Schools Using VidyaFrame', value: '50', suffix: '+', icon: '/hero/schools.webp' },
  { label: 'Happy Teachers', value: '500', suffix: '+', icon: '/hero/teachers.webp' },
];

// ─── ASSETS (from Maths_topics.md CSV data) ──────────────────
export const assets: Asset[] = [
  {
    id: 1,
    title: 'Counting Chart 1 to 5',
    slug: 'counting-chart-1-to-5',
    description: 'A chart listing numbers 1 to 5 to help children practice counting and number recognition.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-5', 'count chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/counting-chart-1-to-5.webp',
    imageMasterUrl: '/assets/masters/counting-chart-1-to-5.png',
    downloads: 1245,
    views: 8920,
    createdAt: '2025-01-15',
  },
  {
    id: 2,
    title: 'Number Names 1 to 5 Chart',
    slug: 'number-names-1-to-5-chart',
    description: 'A chart displaying numbers 1–5 alongside their names, reinforcing basic number-word association.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Number Names',
    tags: ['number names', 'numbers', '1-5'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/number-names-1-to-5-chart.webp',
    imageMasterUrl: '/assets/masters/number-names-1-to-5-chart.png',
    downloads: 980,
    views: 6540,
    createdAt: '2025-01-20',
  },
  {
    id: 3,
    title: 'Primary Colors Chart',
    slug: 'primary-colors-chart',
    description: 'A colorful chart introducing the three primary colors (Red, Yellow, Blue) with descriptive details.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Colors',
    tags: ['colors', 'chart', 'primary colors', 'english'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/primary-colors-chart.webp',
    imageMasterUrl: '/assets/masters/primary-colors-chart.png',
    downloads: 2100,
    views: 15300,
    createdAt: '2025-01-25',
    hasRealMaster: true,
  },
  {
    id: 4,
    title: 'Basic Shapes Chart',
    slug: 'basic-shapes-chart-nursery',
    description: 'A chart showing common 2D shapes (circle, square, triangle, etc.) with labels to teach shape recognition.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Shapes',
    tags: ['shapes', 'chart', 'circle', 'square', 'triangle'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/basic-shapes-chart.webp',
    imageMasterUrl: '/assets/masters/basic-shapes-chart.png',
    downloads: 1870,
    views: 12400,
    createdAt: '2025-02-01',
  },
  {
    id: 5,
    title: 'Size Comparison Chart (Big vs Small)',
    slug: 'size-comparison-chart-big-vs-small',
    description: 'A comparison chart illustrating big vs small objects to teach size and relative comparison.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Comparison',
    tags: ['size', 'big', 'small', 'comparison'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/size-comparison-chart.webp',
    imageMasterUrl: '/assets/masters/size-comparison-chart.png',
    downloads: 765,
    views: 5230,
    createdAt: '2025-02-05',
  },
  {
    id: 6,
    title: 'AB Pattern Worksheet (Shapes)',
    slug: 'ab-pattern-worksheet-shapes',
    description: 'A worksheet with AB repeating patterns using shapes that children complete to reinforce pattern skills.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Patterns',
    tags: ['pattern', 'AB pattern', 'shapes', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/ab-pattern-worksheet.webp',
    imageMasterUrl: '/assets/masters/ab-pattern-worksheet.png',
    downloads: 1340,
    views: 9100,
    createdAt: '2025-02-10',
  },
  {
    id: 7,
    title: 'More or Less Worksheet (1-5)',
    slug: 'more-or-less-worksheet-1-5',
    description: 'A worksheet for comparing quantities (more vs less) using numbers 1–5, teaching basic comparison.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Comparison',
    tags: ['more', 'less', 'compare', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Medium',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/more-or-less-worksheet.webp',
    imageMasterUrl: '/assets/masters/more-or-less-worksheet.png',
    downloads: 560,
    views: 3200,
    createdAt: '2025-02-15',
  },
  {
    id: 8,
    title: 'Color Sorting Worksheet',
    slug: 'color-sorting-worksheet',
    description: 'A worksheet activity where students sort objects by color, reinforcing color recognition.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Colors',
    tags: ['sorting', 'colors', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Medium',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/color-sorting-worksheet.webp',
    imageMasterUrl: '/assets/masters/color-sorting-worksheet.png',
    downloads: 430,
    views: 2890,
    createdAt: '2025-02-20',
  },
  {
    id: 9,
    title: 'Counting Chart 1 to 10',
    slug: 'counting-chart-1-to-10-nursery',
    description: 'A chart listing numbers 1 to 10 to support counting skills with visual cues.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/counting-chart-1-to-10.webp',
    imageMasterUrl: '/assets/masters/counting-chart-1-to-10.png',
    downloads: 3200,
    views: 21000,
    createdAt: '2025-03-01',
    hasRealMaster: true,
  },
  {
    id: 50,
    title: 'Counting Worksheet 1 to 10',
    slug: 'counting-worksheet-1-to-10',
    description: 'A practice worksheet to help kids count objects from 1 to 10 and practice writing numbers.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'worksheet', 'maths practice'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/counting-worksheet-1-to-10.webp',
    imageMasterUrl: '/assets/masters/counting-worksheet-1-to-10.png',
    downloads: 1420,
    views: 7800,
    createdAt: '2026-06-17',
    hasRealMaster: true,
  },
  {
    id: 10,
    title: 'Star of the Month Certificate',
    slug: 'star-of-the-month-certificate',
    description: "A template certificate to award a 'Star of the Month' for recognizing outstanding student achievement.",
    category: 'Certificate',
    classLevel: 'Nursery',
    topic: 'Awards',
    tags: ['certificate', 'award', 'star', 'achievement'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Low',
    estimatedAssets: 1,
    imagePreviewUrl: '/assets/previews/star-of-the-month-certificate.webp',
    imageMasterUrl: '/assets/masters/star-of-the-month-certificate.png',
    downloads: 890,
    views: 4500,
    createdAt: '2025-03-05',
  },
  {
    id: 11,
    title: 'Counting Chart 1 to 10',
    slug: 'counting-chart-1-to-10-lkg',
    description: 'A chart listing numbers 1 to 10 to help LKG children practice counting and number recognition.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/counting-chart-1-to-10-lkg.webp',
    imageMasterUrl: '/assets/masters/counting-chart-1-to-10-lkg.png',
    downloads: 2850,
    views: 18700,
    createdAt: '2025-03-10',
  },
  {
    id: 12,
    title: 'Number Names 1 to 10 Chart',
    slug: 'number-names-1-to-10-chart',
    description: 'A chart showing numbers 1–10 and their English names, reinforcing the link between numerals and words.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Number Names',
    tags: ['number names', 'numbers', '1-10'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/number-names-1-to-10-chart.webp',
    imageMasterUrl: '/assets/masters/number-names-1-to-10-chart.png',
    downloads: 1900,
    views: 13200,
    createdAt: '2025-03-15',
  },
  {
    id: 13,
    title: 'Missing Numbers Worksheet (1-10)',
    slug: 'missing-numbers-worksheet-1-10',
    description: 'A worksheet where students fill in missing numbers in a 1–10 sequence, practicing number order.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Number Sequence',
    tags: ['missing numbers', 'sequence', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/missing-numbers-worksheet.webp',
    imageMasterUrl: '/assets/masters/missing-numbers-worksheet.png',
    downloads: 1560,
    views: 10800,
    createdAt: '2025-03-20',
  },
  {
    id: 14,
    title: 'Basic Shapes Chart',
    slug: 'basic-shapes-chart-lkg',
    description: 'A chart illustrating basic 2D shapes (circle, rectangle, triangle, etc.) for shape identification.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Shapes',
    tags: ['shapes', 'circle', 'square', 'rectangle', 'triangle'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/basic-shapes-chart-lkg.webp',
    imageMasterUrl: '/assets/masters/basic-shapes-chart-lkg.png',
    downloads: 1670,
    views: 11500,
    createdAt: '2025-03-25',
  },
  {
    id: 15,
    title: 'Greater Than Less Than Chart (1-20)',
    slug: 'greater-than-less-than-chart-1-20',
    description: "A chart comparing numbers 1–20 using '>' and '<' to teach greater/less-than concepts.",
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Comparison',
    tags: ['greater than', 'less than', 'compare', 'numbers'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/greater-than-less-than-chart.webp',
    imageMasterUrl: '/assets/masters/greater-than-less-than-chart.png',
    downloads: 1230,
    views: 8900,
    createdAt: '2025-04-01',
  },
  {
    id: 16,
    title: 'Ascending and Descending Order Worksheet (1-20)',
    slug: 'ascending-and-descending-order-worksheet-1-20',
    description: 'A worksheet for arranging numbers in ascending or descending order within 1–20 to practice sequencing.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Number Sequence',
    tags: ['ascending order', 'descending order', 'sequence', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/ascending-descending-order.webp',
    imageMasterUrl: '/assets/masters/ascending-descending-order.png',
    downloads: 1100,
    views: 7600,
    createdAt: '2025-04-05',
  },
  {
    id: 17,
    title: 'Simple Patterns Worksheet',
    slug: 'simple-patterns-worksheet',
    description: 'A worksheet with simple repeating AB or ABC patterns for students to complete.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Patterns',
    tags: ['pattern', 'AB pattern', 'ABC pattern', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/simple-patterns-worksheet.webp',
    imageMasterUrl: '/assets/masters/simple-patterns-worksheet.png',
    downloads: 890,
    views: 6100,
    createdAt: '2025-04-10',
  },
  {
    id: 18,
    title: 'Tens Frames Counting Chart',
    slug: 'tens-frames-counting-chart',
    description: 'A chart showing tens frames (arrays of ten) with filled and empty slots to practice counting and basic addition.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Counting',
    tags: ['tens frame', 'counting', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/tens-frames-counting-chart.webp',
    imageMasterUrl: '/assets/masters/tens-frames-counting-chart.png',
    downloads: 1340,
    views: 9200,
    createdAt: '2025-04-15',
  },
  {
    id: 19,
    title: 'Match Objects to Numbers Worksheet',
    slug: 'match-objects-to-numbers-worksheet',
    description: 'A worksheet where students match pictures of objects to the correct numeral, reinforcing counting skills.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Counting',
    tags: ['matching', 'numbers', 'objects', 'counting'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Medium',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/match-objects-to-numbers.webp',
    imageMasterUrl: '/assets/masters/match-objects-to-numbers.png',
    downloads: 670,
    views: 4500,
    createdAt: '2025-04-20',
  },
  {
    id: 20,
    title: 'Tall and Short Chart',
    slug: 'tall-and-short-chart',
    description: 'A chart contrasting tall and short objects to introduce concepts of height and comparison.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Measurement',
    tags: ['tall', 'short', 'height', 'comparison'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Medium',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/tall-and-short-chart.webp',
    imageMasterUrl: '/assets/masters/tall-and-short-chart.png',
    downloads: 540,
    views: 3800,
    createdAt: '2025-04-25',
  },
  {
    id: 21,
    title: 'Money Chart (Coins Up To ₹5)',
    slug: 'money-chart-coins-up-to-5',
    description: 'A chart showing Indian coins (₹1, ₹2, ₹5) to introduce basic currency and money recognition.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Money',
    tags: ['money', 'coins', 'rupee'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/money-chart-coins-5.webp',
    imageMasterUrl: '/assets/masters/money-chart-coins-5.png',
    downloads: 1450,
    views: 10200,
    createdAt: '2025-05-01',
  },
  {
    id: 22,
    title: 'Math Whiz Certificate',
    slug: 'math-whiz-certificate',
    description: "A template certificate celebrating mathematical achievement (e.g., 'Math Whiz'), to motivate students.",
    category: 'Certificate',
    classLevel: 'LKG',
    topic: 'Awards',
    tags: ['certificate', 'award', 'math', 'achievement'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Low',
    estimatedAssets: 1,
    imagePreviewUrl: '/assets/previews/math-whiz-certificate.webp',
    imageMasterUrl: '/assets/masters/math-whiz-certificate.png',
    downloads: 670,
    views: 3400,
    createdAt: '2025-05-05',
  },
  {
    id: 23,
    title: 'Counting Chart 1 to 50',
    slug: 'counting-chart-1-to-50',
    description: 'A colorful chart listing numbers 1 to 50, helping UKG students practice counting and number recognition.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-50', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/counting-chart-1-to-50.webp',
    imageMasterUrl: '/assets/masters/counting-chart-1-to-50.png',
    downloads: 2670,
    views: 17800,
    createdAt: '2025-05-10',
  },
  {
    id: 24,
    title: 'Number Names 1 to 20 Chart',
    slug: 'number-names-1-to-20-chart',
    description: 'A chart with numbers 1–20 and their English names to reinforce number-word relationships.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Number Names',
    tags: ['number names', 'numbers', '1-20'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/number-names-1-to-20-chart.webp',
    imageMasterUrl: '/assets/masters/number-names-1-to-20-chart.png',
    downloads: 1780,
    views: 12300,
    createdAt: '2025-05-15',
  },
  {
    id: 25,
    title: 'Place Value Chart (Tens and Ones)',
    slug: 'place-value-chart-tens-ones',
    description: 'A place-value chart showing tens and ones for two-digit numbers, introducing number composition.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Place Value',
    tags: ['place value', 'tens', 'ones', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/place-value-chart.webp',
    imageMasterUrl: '/assets/masters/place-value-chart.png',
    downloads: 1450,
    views: 9800,
    createdAt: '2025-05-20',
  },
  {
    id: 26,
    title: 'Odd and Even Numbers Chart (1-50)',
    slug: 'odd-and-even-numbers-chart-1-50',
    description: 'A chart separating numbers 1–50 into odd and even to help students distinguish between the two categories.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Odd Even',
    tags: ['odd', 'even', 'numbers', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/odd-even-chart.webp',
    imageMasterUrl: '/assets/masters/odd-even-chart.png',
    downloads: 1230,
    views: 8400,
    createdAt: '2025-05-25',
  },
  {
    id: 27,
    title: 'Basic Addition Worksheet (2-digit)',
    slug: 'basic-addition-worksheet-2-digit',
    description: 'A worksheet of simple two-digit addition problems for UKG to practice basic addition skills.',
    category: 'Worksheet',
    classLevel: 'UKG',
    topic: 'Addition',
    tags: ['addition', 'worksheet', '2-digit'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/addition-worksheet-2-digit.webp',
    imageMasterUrl: '/assets/masters/addition-worksheet-2-digit.png',
    downloads: 2340,
    views: 15600,
    createdAt: '2025-06-01',
  },
  {
    id: 28,
    title: 'Basic Subtraction Worksheet (2-digit)',
    slug: 'basic-subtraction-worksheet-2-digit',
    description: 'A worksheet of simple two-digit subtraction problems for UKG to practice basic subtraction.',
    category: 'Worksheet',
    classLevel: 'UKG',
    topic: 'Subtraction',
    tags: ['subtraction', 'worksheet', '2-digit'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/subtraction-worksheet-2-digit.webp',
    imageMasterUrl: '/assets/masters/subtraction-worksheet-2-digit.png',
    downloads: 2100,
    views: 14200,
    createdAt: '2025-06-05',
  },
  {
    id: 29,
    title: 'Money Chart (Rupee Coins and ₹ Notes)',
    slug: 'money-chart-rupee-coins-and-notes',
    description: 'A chart showing common rupee coins and notes, familiarizing students with the Indian currency.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Money',
    tags: ['money', 'coins', 'notes', 'rupee'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/money-chart-rupee.webp',
    imageMasterUrl: '/assets/masters/money-chart-rupee.png',
    downloads: 1670,
    views: 11400,
    createdAt: '2025-06-10',
  },
  {
    id: 30,
    title: 'Clock Chart (Hour and Half-Hour)',
    slug: 'clock-chart-hour-and-half-hour-ukg',
    description: 'A clock face chart highlighting the hour and half-hour marks to teach students how to tell time.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Time',
    tags: ['clock', 'time', 'hour', 'half-hour'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/clock-chart-ukg.webp',
    imageMasterUrl: '/assets/masters/clock-chart-ukg.png',
    downloads: 1890,
    views: 13100,
    createdAt: '2025-06-15',
  },
  {
    id: 31,
    title: 'Calendar Poster (Days and Months)',
    slug: 'calendar-poster-days-months',
    description: 'A poster displaying days of the week and months of the year, helping children learn calendar basics.',
    category: 'Poster',
    classLevel: 'UKG',
    topic: 'Calendar',
    tags: ['calendar', 'days', 'months', 'poster'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Low',
    estimatedAssets: 1,
    imagePreviewUrl: '/assets/previews/calendar-poster.webp',
    imageMasterUrl: '/assets/masters/calendar-poster.png',
    downloads: 780,
    views: 5200,
    createdAt: '2025-06-20',
  },
  {
    id: 32,
    title: '2D Shapes Chart',
    slug: '2d-shapes-chart',
    description: 'A chart listing common 2D shapes (circle, square, triangle, rectangle) with examples for identification.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Shapes',
    tags: ['2D shapes', 'circle', 'square', 'triangle', 'rectangle'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/2d-shapes-chart.webp',
    imageMasterUrl: '/assets/masters/2d-shapes-chart.png',
    downloads: 1560,
    views: 10800,
    createdAt: '2025-06-25',
  },
  {
    id: 33,
    title: '3D Shapes Chart',
    slug: '3d-shapes-chart',
    description: 'A chart showing common 3D shapes (cube, sphere, cylinder, cone) with examples, introducing basic geometry.',
    category: 'Chart',
    classLevel: 'UKG',
    topic: 'Shapes',
    tags: ['3D shapes', 'cube', 'sphere', 'cylinder', 'cone'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/3d-shapes-chart.webp',
    imageMasterUrl: '/assets/masters/3d-shapes-chart.png',
    downloads: 1340,
    views: 9200,
    createdAt: '2025-07-01',
  },
  {
    id: 34,
    title: 'What Comes Next Worksheet (1-50)',
    slug: 'what-comes-next-worksheet-1-50',
    description: 'A worksheet where students fill in missing numbers in sequences up to 50, reinforcing number patterns.',
    category: 'Worksheet',
    classLevel: 'UKG',
    topic: 'Number Sequence',
    tags: ['sequence', 'what comes next', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/what-comes-next-worksheet.webp',
    imageMasterUrl: '/assets/masters/what-comes-next-worksheet.png',
    downloads: 1120,
    views: 7800,
    createdAt: '2025-07-05',
  },
  {
    id: 35,
    title: 'Compare Numbers Worksheet (Greater/Less)',
    slug: 'compare-numbers-worksheet',
    description: "A worksheet for comparing pairs of numbers (using '>', '<') to identify which is greater or lesser.",
    category: 'Worksheet',
    classLevel: 'UKG',
    topic: 'Comparison',
    tags: ['compare', 'greater than', 'less than', 'numbers'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Medium',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/compare-numbers-worksheet.webp',
    imageMasterUrl: '/assets/masters/compare-numbers-worksheet.png',
    downloads: 890,
    views: 6100,
    createdAt: '2025-07-10',
  },
  {
    id: 36,
    title: 'Super Student Certificate',
    slug: 'super-student-certificate',
    description: "An award certificate template (e.g., 'Super Student') for recognizing UKG student achievements or behavior.",
    category: 'Certificate',
    classLevel: 'UKG',
    topic: 'Awards',
    tags: ['certificate', 'award', 'achievement'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Low',
    estimatedAssets: 1,
    imagePreviewUrl: '/assets/previews/super-student-certificate.webp',
    imageMasterUrl: '/assets/masters/super-student-certificate.png',
    downloads: 560,
    views: 3200,
    createdAt: '2025-07-15',
  },
  {
    id: 37,
    title: 'Counting Chart 1 to 100',
    slug: 'counting-chart-1-to-100',
    description: 'A 1–100 number chart to support counting practice and number recognition in first grade.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-100', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/counting-chart-1-to-100.webp',
    imageMasterUrl: '/assets/masters/counting-chart-1-to-100.png',
    downloads: 4500,
    views: 32000,
    createdAt: '2025-07-20',
  },
  {
    id: 38,
    title: 'Number Names Chart 1 to 100',
    slug: 'number-names-chart-1-to-100',
    description: 'A chart pairing each number from 1–100 with its name, reinforcing reading and writing of numerals.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Number Names',
    tags: ['number names', 'numbers', '1-100', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/number-names-1-to-100.webp',
    imageMasterUrl: '/assets/masters/number-names-1-to-100.png',
    downloads: 3200,
    views: 22000,
    createdAt: '2025-07-25',
  },
  {
    id: 39,
    title: 'Basic 2D Shapes Chart',
    slug: 'basic-2d-shapes-chart',
    description: 'A chart showing basic 2D shapes (circle, square, triangle, rectangle) to help first graders recognize flat shapes.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Shapes',
    tags: ['shapes', '2D shapes', 'circle', 'square', 'triangle'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/basic-2d-shapes-chart-1.webp',
    imageMasterUrl: '/assets/masters/basic-2d-shapes-chart-1.png',
    downloads: 1890,
    views: 13500,
    createdAt: '2025-08-01',
  },
  {
    id: 40,
    title: 'Basic 3D Shapes Chart',
    slug: 'basic-3d-shapes-chart',
    description: 'A chart illustrating basic 3D shapes (cube, sphere, cone, cylinder) and their names, introducing solid geometry.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Shapes',
    tags: ['shapes', '3D shapes', 'cube', 'sphere', 'cone'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/basic-3d-shapes-chart-1.webp',
    imageMasterUrl: '/assets/masters/basic-3d-shapes-chart-1.png',
    downloads: 1560,
    views: 10800,
    createdAt: '2025-08-05',
  },
  {
    id: 41,
    title: 'Addition Worksheet (within 20)',
    slug: 'addition-worksheet-within-20',
    description: 'A worksheet with addition problems (sums up to 20) for first graders to practice addition skills.',
    category: 'Worksheet',
    classLevel: '1',
    topic: 'Addition',
    tags: ['addition', 'worksheet', '2-digit'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/addition-worksheet-within-20.webp',
    imageMasterUrl: '/assets/masters/addition-worksheet-within-20.png',
    downloads: 3450,
    views: 24000,
    createdAt: '2025-08-10',
  },
  {
    id: 42,
    title: 'Subtraction Worksheet (within 20)',
    slug: 'subtraction-worksheet-within-20',
    description: 'A worksheet with subtraction problems (up to 20) to give first graders practice in basic subtraction.',
    category: 'Worksheet',
    classLevel: '1',
    topic: 'Subtraction',
    tags: ['subtraction', 'worksheet', '2-digit'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/subtraction-worksheet-within-20.webp',
    imageMasterUrl: '/assets/masters/subtraction-worksheet-within-20.png',
    downloads: 2890,
    views: 19800,
    createdAt: '2025-08-15',
  },
  {
    id: 43,
    title: 'Clock Chart (Hour and Half-Hour)',
    slug: 'clock-chart-hour-and-half-hour',
    description: 'A chart of an analog clock highlighting the hour and half-hour to teach time-telling.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Time',
    tags: ['time', 'clock', 'hour', 'half-hour'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/clock-chart-hour-half-hour.webp',
    imageMasterUrl: '/assets/masters/clock-chart-hour-half-hour.png',
    downloads: 2100,
    views: 14500,
    createdAt: '2025-08-20',
  },
  {
    id: 44,
    title: 'Money Chart (Indian Coins)',
    slug: 'money-chart-indian-coins',
    description: 'A chart showing common Indian coins (₹1, ₹2, ₹5, ₹10) to familiarize students with money values.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Money',
    tags: ['money', 'coins', 'rupee'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/money-chart-indian-coins.webp',
    imageMasterUrl: '/assets/masters/money-chart-indian-coins.png',
    downloads: 1780,
    views: 12200,
    createdAt: '2025-08-25',
  },
  {
    id: 45,
    title: 'Place Value Chart (Ones and Tens)',
    slug: 'place-value-chart-ones-tens',
    description: 'A chart showing ones and tens columns for two-digit numbers to teach place value concepts.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Place Value',
    tags: ['place value', 'ones', 'tens'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/place-value-chart-ones-tens.webp',
    imageMasterUrl: '/assets/masters/place-value-chart-ones-tens.png',
    downloads: 1560,
    views: 10800,
    createdAt: '2025-09-01',
  },
  {
    id: 46,
    title: 'Even and Odd Numbers Chart (1-20)',
    slug: 'even-and-odd-numbers-chart-1-20',
    description: 'A chart listing even and odd numbers from 1 to 20 in separate columns for easy reference.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Odd Even',
    tags: ['even', 'odd', 'numbers', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/even-odd-chart-1-20.webp',
    imageMasterUrl: '/assets/masters/even-odd-chart-1-20.png',
    downloads: 1340,
    views: 9200,
    createdAt: '2025-09-05',
  },
  {
    id: 47,
    title: 'Missing Number Worksheet (1-50)',
    slug: 'missing-number-worksheet-1-50',
    description: 'A worksheet where children fill in missing numbers in a 1–50 sequence, practicing counting order.',
    category: 'Worksheet',
    classLevel: '1',
    topic: 'Number Sequence',
    tags: ['missing numbers', 'sequence', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/missing-number-worksheet-1-50.webp',
    imageMasterUrl: '/assets/masters/missing-number-worksheet-1-50.png',
    downloads: 1890,
    views: 13200,
    createdAt: '2025-09-10',
  },
  {
    id: 48,
    title: 'Pictograph Chart (Example Graph)',
    slug: 'pictograph-chart-example-graph',
    description: 'A pictograph chart (example with icons) illustrating how data can be represented visually.',
    category: 'Chart',
    classLevel: '1',
    topic: 'Data Handling',
    tags: ['pictograph', 'graph', 'data', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/pictograph-chart.webp',
    imageMasterUrl: '/assets/masters/pictograph-chart.png',
    downloads: 980,
    views: 6700,
    createdAt: '2025-09-15',
  },
  {
    id: 49,
    title: 'AB Pattern Worksheet (Colors/Numbers)',
    slug: 'ab-pattern-worksheet-colors-numbers',
    description: 'A worksheet with AB patterns using colors or numbers, helping students complete and identify the rule.',
    category: 'Worksheet',
    classLevel: '1',
    topic: 'Patterns',
    tags: ['pattern', 'AB pattern', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/ab-pattern-worksheet-colors.webp',
    imageMasterUrl: '/assets/masters/ab-pattern-worksheet-colors.png',
    downloads: 1120,
    views: 7800,
    createdAt: '2025-09-20',
  },
  {
    id: 50,
    title: 'Skip Counting Chart (by 2, 5, 10)',
    slug: 'skip-counting-chart-by-2-5-10',
    description: 'A chart showing sequences of numbers counting by 2s, 5s, and 10s to teach skip-counting patterns.',
    category: 'Chart',
    classLevel: '2',
    topic: 'Skip Counting',
    tags: ['skip counting', '2s', '5s', '10s'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/skip-counting-chart.webp',
    imageMasterUrl: '/assets/masters/skip-counting-chart.png',
    downloads: 2340,
    views: 16200,
    createdAt: '2025-09-25',
  },
  {
    id: 101,
    title: 'Primary Colors Bilingual Chart (Hindi/English)',
    slug: 'primary-colors-bilingual-chart',
    description: 'A bilingual chart introducing the three basic colors in English and Hindi with interactive descriptions.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Colors',
    tags: ['colors', 'chart', 'bilingual', 'hindi', 'english'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/primary-colors-bilingual-chart.webp',
    imageMasterUrl: '/assets/masters/primary-colors-bilingual-chart.png',
    downloads: 1450,
    views: 8900,
    createdAt: '2025-02-02',
    hasRealMaster: true,
  },
  {
    id: 102,
    title: 'Colours Name Bilingual Chart (Hindi/English - 11 Colors)',
    slug: 'colours-name-bilingual-chart',
    description: 'A bilingual chart to learn 11 colors in both English and Hindi with visual illustrations.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Colors',
    tags: ['colors', 'chart', 'bilingual', 'hindi', 'english', '11 colors'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/colours-name-bilingual-chart.webp',
    imageMasterUrl: '/assets/masters/colours-name-bilingual-chart.png',
    downloads: 1890,
    views: 9200,
    createdAt: '2025-02-03',
    hasRealMaster: true,
  },
  {
    id: 103,
    title: 'Colours Name Chart (English - 20 Colors)',
    slug: 'colours-name-chart',
    description: 'An educational chart illustrating 20 different colors in English with clear examples.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Colors',
    tags: ['colors', 'chart', 'english', '20 colors'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/colours-name-chart.webp',
    imageMasterUrl: '/assets/masters/colours-name-chart.png',
    downloads: 2150,
    views: 11400,
    createdAt: '2025-02-04',
    hasRealMaster: true,
  },
  {
    id: 104,
    title: 'Colours Name Chart (English - 11 Colors)',
    slug: 'colours-name-11-colours-chart',
    description: 'A basic educational chart showcasing 11 colors in English with simple illustrations.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Colors',
    tags: ['colors', 'chart', 'english', '11 colors'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/colours-name-11-colours-chart.webp',
    imageMasterUrl: '/assets/masters/colours-name-11-colours-chart.png',
    downloads: 1200,
    views: 6800,
    createdAt: '2025-02-05',
    hasRealMaster: true,
  },
  {
    id: 105,
    title: 'Colours Name Bilingual Chart (Hindi/English - 20 Colors)',
    slug: 'colours-name-bilingual-20-colours-chart',
    description: 'A comprehensive bilingual chart illustrating 20 colors in English and Hindi with pictures.',
    category: 'Chart',
    classLevel: 'LKG',
    topic: 'Colors',
    tags: ['colors', 'chart', 'bilingual', 'hindi', 'english', '20 colors'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/colours-name-bilingual-20-colours-chart.webp',
    imageMasterUrl: '/assets/masters/colours-name-bilingual-20-colours-chart.png',
    downloads: 2450,
    views: 12500,
    createdAt: '2025-02-06',
    hasRealMaster: true,
  },
  {
    id: 106,
    title: 'Colours Name Bilingual Chart (Hindi/English - 11 Colors v2)',
    slug: 'colours-name-bilingual-chart-v2',
    description: 'Alternative layout of the bilingual chart for 11 colors in Hindi and English.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Colors',
    tags: ['colors', 'chart', 'bilingual', 'hindi', 'english', '11 colors'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Medium',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/colours-name-bilingual-chart-v2.webp',
    imageMasterUrl: '/assets/masters/colours-name-bilingual-chart-v2.png',
    downloads: 720,
    views: 4500,
    createdAt: '2025-02-07',
    hasRealMaster: true,
  },
  {
    id: 110,
    title: 'A to Z Alphabet Chart (Bilingual English/Hindi)',
    slug: 'a-to-z-alphabet-bilingual-chart',
    description: 'A beautiful educational chart showing capital letters A to Z with English and Hindi names for all objects.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'english', 'hindi', 'bilingual', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-bilingual-chart.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-bilingual-chart.png',
    downloads: 3200,
    views: 19800,
    createdAt: '2025-03-01',
    hasRealMaster: true,
  },
  {
    id: 111,
    title: 'A to Z Alphabet Bilingual Practice Worksheet (Look, Write & Learn)',
    slug: 'a-to-z-alphabet-bilingual-practice-worksheet',
    description: 'Practice writing English and Hindi names for pictures from A to Z in this comprehensive bilingual worksheet.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'english', 'hindi', 'bilingual', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-bilingual-practice-worksheet.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-bilingual-practice-worksheet.png',
    downloads: 2450,
    views: 15600,
    createdAt: '2025-03-02',
    hasRealMaster: true,
  },
  {
    id: 112,
    title: 'A to Z Alphabet Bilingual Worksheet (English + Hindi)',
    slug: 'a-to-z-alphabet-bilingual-worksheet',
    description: 'Bilingual worksheet focusing on writing names in English and Hindi, matching letters, and missing letter grids.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'english', 'hindi', 'bilingual', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-bilingual-worksheet.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-bilingual-worksheet.png',
    downloads: 2100,
    views: 12400,
    createdAt: '2025-03-03',
    hasRealMaster: true,
  },
  {
    id: 113,
    title: 'A to Z Alphabet Practice Worksheet',
    slug: 'a-to-z-alphabet-practice-worksheet',
    description: 'Alphabet practice worksheet with missing letters write-up, letter matching to pictures, and beginning letters selection.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'english', 'practice', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-practice-worksheet.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-practice-worksheet.png',
    downloads: 1950,
    views: 10200,
    createdAt: '2025-03-04',
    hasRealMaster: true,
  },
  {
    id: 114,
    title: 'A to Z Alphabet Letters and Words Worksheet',
    slug: 'a-to-z-alphabet-letters-words-worksheet',
    description: 'Fun worksheet featuring letter tracking, coloring, word completion, and bonus letter sequence activities.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'english', 'letters', 'words', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-letters-words-worksheet.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-letters-words-worksheet.png',
    downloads: 1850,
    views: 9600,
    createdAt: '2025-03-05',
    hasRealMaster: true,
  },
  {
    id: 115,
    title: 'A to Z Alphabet Words Worksheet (Learn with Pictures)',
    slug: 'a-to-z-alphabet-words-worksheet',
    description: 'Fill missing letters, write the first letter of each picture, and complete A to Z words in this rich word-picture worksheet.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'words', 'pictures', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-words-worksheet.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-words-worksheet.png',
    downloads: 2700,
    views: 14200,
    createdAt: '2025-03-06',
    hasRealMaster: true,
  },
  {
    id: 116,
    title: 'A to Z Alphabet Spelling Worksheet',
    slug: 'a-to-z-alphabet-spelling-worksheet',
    description: 'Look at the picture and write the correct spelling for each letter A to Z in this clean educational worksheet.',
    category: 'Worksheet',
    classLevel: 'UKG',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'spelling', 'writing', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-spelling-worksheet.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-spelling-worksheet.png',
    downloads: 1650,
    views: 8900,
    createdAt: '2025-03-07',
    hasRealMaster: true,
  },
  {
    id: 117,
    title: 'A to Z Alphabet Activities Worksheet (Word Search & Unscramble)',
    slug: 'a-to-z-alphabet-activities-worksheet',
    description: 'An advanced activity sheet containing letter tracing, image naming, unscrambling, letter patterns, and word search puzzles.',
    category: 'Worksheet',
    classLevel: 'UKG',
    topic: 'Alphabet',
    tags: ['alphabet', 'a-to-z', 'activities', 'word search', 'unscramble', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/a-to-z-alphabet-activities-worksheet.webp',
    imageMasterUrl: '/assets/masters/a-to-z-alphabet-activities-worksheet.png',
    downloads: 3400,
    views: 22000,
    createdAt: '2025-03-08',
    hasRealMaster: true,
  },
  {
    id: 120,
    title: 'Number Counting Chart 1 to 10 (Bilingual English/Hindi)',
    slug: 'counting-1-to-10-bilingual-chart',
    description: 'A bilingual chart counting 1 to 10 with counting objects, featuring numbers and words in English and Hindi.',
    category: 'Chart',
    classLevel: 'Nursery',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'bilingual', 'hindi', 'english', 'chart'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 2,
    imagePreviewUrl: '/assets/previews/counting-1-to-10-bilingual-chart.webp',
    imageMasterUrl: '/assets/masters/counting-1-to-10-bilingual-chart.png',
    downloads: 2800,
    views: 17400,
    createdAt: '2025-04-01',
    hasRealMaster: true,
  },
  {
    id: 121,
    title: 'Number Counting Worksheet 1 to 10 (Bilingual English/Hindi)',
    slug: 'counting-1-to-10-bilingual-worksheet',
    description: 'Bilingual number counting practice sheet to trace numbers, write counts, and trace number words in English and Hindi.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'bilingual', 'hindi', 'english', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/counting-1-to-10-bilingual-worksheet.webp',
    imageMasterUrl: '/assets/masters/counting-1-to-10-bilingual-worksheet.png',
    downloads: 2150,
    views: 13900,
    createdAt: '2025-04-02',
    hasRealMaster: true,
  },
  {
    id: 122,
    title: 'Number Counting Worksheet 1 to 10 (Alternative Layout)',
    slug: 'counting-worksheet-1-to-10-v2',
    description: 'Alternative layout for 1-10 number counting worksheet, focused on object counting, tracing numbers, and tracing English words.',
    category: 'Worksheet',
    classLevel: 'Nursery',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'english', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'Medium',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/counting-worksheet-1-to-10-v2.webp',
    imageMasterUrl: '/assets/masters/counting-worksheet-1-to-10-v2.png',
    downloads: 980,
    views: 5600,
    createdAt: '2025-04-03',
    hasRealMaster: true,
  },
  {
    id: 123,
    title: 'Number Practice Worksheet 1 to 10 (Learn & Write)',
    slug: 'number-practice-1-to-10-worksheet',
    description: 'A comprehensive number practice worksheet featuring tracing, missing numbers, matching, and coloring activities for numbers 1 to 10.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'practice', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/number-practice-1-to-10-worksheet.webp',
    imageMasterUrl: '/assets/masters/number-practice-1-to-10-worksheet.png',
    downloads: 3100,
    views: 18400,
    createdAt: '2025-04-04',
    hasRealMaster: true,
  },
  {
    id: 124,
    title: 'Count Trace Write Worksheet (1-10)',
    slug: 'count-trace-write-worksheet',
    description: 'Trace and write numbers 1 to 10, write number names, count and circle objects, and match objects to numbers.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'trace', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/count-trace-write-worksheet.webp',
    imageMasterUrl: '/assets/masters/count-trace-write-worksheet.png',
    downloads: 2400,
    views: 14800,
    createdAt: '2025-04-05',
    hasRealMaster: true,
  },
  {
    id: 125,
    title: 'Count Trace Write Worksheet with Number Maze (1-10)',
    slug: 'count-trace-write-with-maze-worksheet',
    description: 'Count, trace, and write numbers 1 to 10 with an added bonus Number Maze game to help the bee find the flower.',
    category: 'Worksheet',
    classLevel: 'LKG',
    topic: 'Counting',
    tags: ['counting', 'numbers', '1-10', 'trace', 'maze', 'worksheet'],
    suggestedImageTypes: 'preview,master,pdf,png',
    priority: 'High',
    estimatedAssets: 5,
    imagePreviewUrl: '/assets/previews/count-trace-write-with-maze-worksheet.webp',
    imageMasterUrl: '/assets/masters/count-trace-write-with-maze-worksheet.png',
    downloads: 3800,
    views: 24900,
    createdAt: '2025-04-06',
    hasRealMaster: true,
  },
];

// ─── DATA QUERY FUNCTIONS ─────────────────────────────────────

export function getAssetBySlug(slug: string): Asset | undefined {
  return assets.find((a) => a.slug === slug);
}

export function getAssetsByCategory(category: string): Asset[] {
  const categoryMap: Record<string, string> = {
    charts: 'Chart',
    worksheets: 'Worksheet',
    certificates: 'Certificate',
    posters: 'Poster',
  };
  const cat = categoryMap[category] || category;
  return assets.filter((a) => a.category === cat);
}

export function getAssetsByClass(classLevel: string): Asset[] {
  return assets.filter((a) => a.classLevel === classLevel);
}

export function getAssetsByTopic(topic: string): Asset[] {
  return assets.filter((a) => a.topic.toLowerCase() === topic.toLowerCase());
}

export function searchAssets(query: string, filters?: { category?: string; classLevel?: string; topic?: string }): Asset[] {
  const q = query.toLowerCase().trim();
  let results = assets;

  if (q) {
    results = results.filter(
      (a) =>
        a.title.toLowerCase().includes(q) ||
        a.description.toLowerCase().includes(q) ||
        a.tags.some((t) => t.toLowerCase().includes(q)) ||
        a.topic.toLowerCase().includes(q)
    );
  }

  if (filters?.category) {
    const categoryMap: Record<string, string> = {
      charts: 'Chart',
      worksheets: 'Worksheet',
      certificates: 'Certificate',
      posters: 'Poster',
    };
    const cat = categoryMap[filters.category] || filters.category;
    results = results.filter((a) => a.category === cat);
  }

  if (filters?.classLevel) {
    results = results.filter((a) => a.classLevel === filters.classLevel);
  }

  if (filters?.topic) {
    results = results.filter((a) => a.topic.toLowerCase() === filters.topic!.toLowerCase());
  }

  return results;
}

export function getFeaturedAssets(limit = 8): Asset[] {
  return [...assets]
    .sort((a, b) => b.views - a.views)
    .slice(0, limit);
}

export function getPopularWorksheets(limit = 6): Asset[] {
  return assets
    .filter((a) => a.category === 'Worksheet')
    .sort((a, b) => b.downloads - a.downloads)
    .slice(0, limit);
}

export function getTopics(category?: string): string[] {
  const filtered = category ? getAssetsByCategory(category) : assets;
  return [...new Set(filtered.map((a) => a.topic))];
}

export function getRelatedAssets(asset: Asset, limit = 4): Asset[] {
  return assets
    .filter(
      (a) =>
        a.id !== asset.id &&
        (a.topic === asset.topic || a.classLevel === asset.classLevel || a.category === asset.category)
    )
    .slice(0, limit);
}

// ─── TESTIMONIALS ─────────────────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: 'Priya Sharma',
    role: 'Class Teacher',
    school: 'Delhi Public School, Noida',
    avatar: '',
    content: 'VidyaFrame has transformed how I prepare classroom materials. The charts are beautiful and the school branding feature saves me hours every week!',
    rating: 5,
  },
  {
    id: 2,
    name: 'Rajesh Kumar',
    role: 'Principal',
    school: 'Kendriya Vidyalaya, Lucknow',
    avatar: '',
    content: 'We use VidyaFrame across all our primary classes. The quality of worksheets is excellent and students love the colorful charts on our walls.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Anita Patel',
    role: 'Math Teacher',
    school: 'Ryan International School, Mumbai',
    avatar: '',
    content: 'The counting charts and math worksheets are perfectly aligned with NCERT curriculum. Download is instant and print quality is amazing!',
    rating: 5,
  },
  {
    id: 4,
    name: 'Sunita Verma',
    role: 'Nursery Teacher',
    school: 'Stepping Stones School, Jaipur',
    avatar: '',
    content: 'My nursery students absolutely love the colorful shape charts and pattern worksheets. VidyaFrame understands what young learners need.',
    rating: 5,
  },
];

// ─── FAQ ──────────────────────────────────────────────────────
export const faqItems: FAQItem[] = [
  {
    id: 1,
    question: 'What is VidyaFrame?',
    answer: 'VidyaFrame is an educational resource platform providing ready-made charts, worksheets, certificates, and posters for schools and teachers. All resources are designed for Indian curriculum (NCERT/CBSE) from Nursery to Class 5.',
  },
  {
    id: 2,
    question: 'Is VidyaFrame free to use?',
    answer: 'VidyaFrame offers both free and premium resources. Basic charts and worksheets are available for free download. Premium resources with school branding features require a subscription.',
  },
  {
    id: 3,
    question: 'How does school branding work?',
    answer: 'Create your school profile once with your logo, name, and theme color. When you download any resource, VidyaFrame automatically applies your school branding — no need to edit each file manually!',
  },
  {
    id: 4,
    question: 'What formats are available for download?',
    answer: 'All resources are available in high-quality PDF and PNG formats. PDFs support A4 and A3 sizes in both portrait and landscape orientations, perfect for classroom printing.',
  },
  {
    id: 5,
    question: 'Are the resources aligned with NCERT/CBSE curriculum?',
    answer: 'Yes! All our charts and worksheets are carefully designed to align with NCERT/CBSE syllabi for Nursery through Class 5. We cover all major math topics including counting, shapes, operations, and more.',
  },
  {
    id: 6,
    question: 'Can I use VidyaFrame resources for commercial purposes?',
    answer: 'VidyaFrame resources are licensed for educational use in schools and classrooms. Redistribution or resale is not permitted. Contact us for institutional licensing.',
  },
];

// ─── FEATURES ─────────────────────────────────────────────────
export const features = [
  {
    icon: '📚',
    title: 'Ready-Made Resources',
    description: 'Browse 1,700+ professionally designed educational charts, worksheets, and certificates.',
    gradient: 'from-teal-500 to-emerald-500',
  },
  {
    icon: '🏫',
    title: 'School Branding',
    description: 'Apply your school logo, name, and colors to any resource with one click.',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    icon: '⚡',
    title: 'Instant Download',
    description: 'Download print-ready PDFs and PNGs instantly. No waiting, no subscriptions needed.',
    gradient: 'from-purple-500 to-indigo-500',
  },
  {
    icon: '🖨️',
    title: 'Print Quality',
    description: 'Every resource is designed at print resolution. Perfect for A4 and A3 classroom displays.',
    gradient: 'from-orange-500 to-amber-500',
  },
];
